version: '2'
services:
  gateway:
    build: ./pigateway
    privileged: true
    restart: always
    
  miner:
    restart: always
    image: quay.io/team-helium/miner:MINER_TAG
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'
    environment:
      - 'REGION_OVERRIDE=AS923_1'
    
  web:
    build: ./web
    privileged: true
    restart: always
    ports: 
      - "80:80"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'
    
volumes:
  miner-data:
  miner-log: 
